version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data1:/var/lib/postgresql/data
      - ./init-scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "${DB_PORT}:5432"

volumes:
  db_data1: